
import Footer from './components/Footer'
import TopNav from './components/TopNav'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${inter.className} ${" dark:bg-black bg-white"}`}>
        <TopNav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
